### ISSUE TITLE
Consider using cmd instead of ctl for Mac OS X

### ISSUE THREAD

**Issue by seancorfield** [jfacorro/clojure-lab#53]
The control keys work well on Windows and Linux but on Mac it's more natural to use command instead. I think there's a standard way in Swing to specify using the "natural" key modifier for the platform (in LightTable, you specify pmeta-x to get ctl-x on Win/Linux and cmd-x on Mac).

**Comment by jfacorro** [comment]
All shortcuts are now expressed with `meta` instead of `ctrl` (e.g.  `meta o` instead of `ctrl o` for opening a file) which resolves to the correct key depending on the platform.

**Comment by seancorfield** [comment]
:+1:

**Comment by jfacorro** [comment]
I didn't realize how annoying this was until a started using OS X! :confounded:
